/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.EmployeeController;
import Controller.UserController;
import Data.Employee;
import Model.UserModel;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Duy.hv150601
 */
public class DashBoard extends javax.swing.JFrame {

    /**
     * Creates new form DashBoard
     */
    public DashBoard() {
        initComponents();
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabelUser = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuEmployeeManagement = new javax.swing.JMenu();
        jMenuItemAddEmployee = new javax.swing.JMenuItem();
        jMenuItemEditEmployeeInformation = new javax.swing.JMenuItem();
        jMenuItemDeleteEmployee = new javax.swing.JMenuItem();
        jMenuItemSearchEmployeeByName = new javax.swing.JMenuItem();
        jMenuItemDisplayAllEmployees = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();

        jMenuItem9.setText("jMenuItem9");

        jMenuItem10.setText("jMenuItem10");

        jMenuItem15.setText("jMenuItem15");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(645, 490));
        getContentPane().setLayout(null);

        jLabelUser.setText("User");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/store2.jpg"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(390, Short.MAX_VALUE)
                .addComponent(jLabelUser)
                .addGap(18, 18, 18)
                .addComponent(jLabelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUser)
                    .addComponent(jLabelUsername))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 640, 460);

        jMenuBar2.setPreferredSize(new java.awt.Dimension(423, 20));

        jMenu1.setText("Quản lý hóa đơn");

        jMenuItem5.setText("Tạo đơn hàng mới");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem4.setText("Tìm kiếm đơn hàng");
        jMenu1.add(jMenuItem4);

        jMenuBar2.add(jMenu1);

        jMenu5.setText("Quản lý kho");

        jMenuItem1.setText("Hiển thị toàn bộ sản phẩm");
        jMenu5.add(jMenuItem1);

        jMenuItem2.setText("Tìm sản phẩm");
        jMenu5.add(jMenuItem2);

        jMenu2.setText("Chỉnh sửa mặt hàng");

        jMenuItem3.setText("Thay đổi");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem6.setText("Xóa");
        jMenu2.add(jMenuItem6);

        jMenu5.add(jMenu2);

        jMenuItem14.setText("Thêm mặt hàng mới");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem14);

        jMenuBar2.add(jMenu5);

        jMenuEmployeeManagement.setText("Quản lý nhân viên");

        jMenuItemAddEmployee.setText("Thêm nhân viên");
        jMenuItemAddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddEmployeeActionPerformed(evt);
            }
        });
        jMenuEmployeeManagement.add(jMenuItemAddEmployee);

        jMenuItemEditEmployeeInformation.setText("Sửa nhân viên");
        jMenuEmployeeManagement.add(jMenuItemEditEmployeeInformation);

        jMenuItemDeleteEmployee.setText("Xóa nhân viên");
        jMenuEmployeeManagement.add(jMenuItemDeleteEmployee);

        jMenuItemSearchEmployeeByName.setText("Tìm nhân viên");
        jMenuEmployeeManagement.add(jMenuItemSearchEmployeeByName);

        jMenuItemDisplayAllEmployees.setText("Hiển thị toàn bộ nhân viên");
        jMenuItemDisplayAllEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDisplayAllEmployeesActionPerformed(evt);
            }
        });
        jMenuEmployeeManagement.add(jMenuItemDisplayAllEmployees);

        jMenuBar2.add(jMenuEmployeeManagement);

        jMenu4.setText("Quản lý tài khoản");

        jMenuItem21.setText("Hiển thị thông tin tài khoản");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem21);

        jMenuItem16.setText("Đổi mật khẩu");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem16);

        jMenuItem20.setText("Đăng xuất");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem20);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
        ChangePassword changePassword= new ChangePassword();
        this.dispose();
        changePassword.setVisible(true);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        // TODO add your handling code here:
        Login login= new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        UserModel userModel= new UserModel();
        UserController userController= new UserController();
        DisplayAccountInformation displayAccountInformation= new DisplayAccountInformation();
        try {
            userModel= userController.getInformation(Login.Username);           
            displayAccountInformation.getjTextFieldFullname().setText(userModel.getUsername());
            displayAccountInformation.getjTextFieldAddress().setText(userModel.getAddress());
            displayAccountInformation.getjTextFieldPhoneNumber().setText(userModel.getPhoneNumber());
            displayAccountInformation.getjTextFieldFullname().setEditable(false);
            displayAccountInformation.getjTextFieldAddress().setEditable(false);
            displayAccountInformation.getjTextFieldPhoneNumber().setEditable(false);
            displayAccountInformation.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItemAddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddEmployeeActionPerformed
        // TODO add your handling code here:
        if (Login.RoleId== 1) {
            AddNewEmployee addNewEmployee= new AddNewEmployee();
            addNewEmployee.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jMenuItemAddEmployeeActionPerformed

    private void jMenuItemDisplayAllEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDisplayAllEmployeesActionPerformed
        // TODO add your handling code here:
        DisplayAllEmployee displayAllEmployee= new DisplayAllEmployee();
        displayAllEmployee.setVisible(true);
        EmployeeController employeeController= new EmployeeController();
        ArrayList<Employee> employees= new ArrayList<>();
        employees= employeeController.getAllEmployees();
        DefaultTableModel defaultTableModel= (DefaultTableModel)displayAllEmployee.getjTableEmployee().getModel();
        for(Employee employee: employees){
           defaultTableModel.addRow(new Object[]{employee.getId(),employee.getFullname(), employee.getAddress(), employee.getPhoneNumber()});
        }
        this.dispose();
        
    }//GEN-LAST:event_jMenuItemDisplayAllEmployeesActionPerformed

    public JLabel getjLabelUsername() {
        return jLabelUsername;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenuEmployeeManagement;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItemAddEmployee;
    private javax.swing.JMenuItem jMenuItemDeleteEmployee;
    private javax.swing.JMenuItem jMenuItemDisplayAllEmployees;
    private javax.swing.JMenuItem jMenuItemEditEmployeeInformation;
    private javax.swing.JMenuItem jMenuItemSearchEmployeeByName;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public JMenu getjMenuEmployeeManagement() {
        return jMenuEmployeeManagement;
    }
}
